# Plan de manejo de riesgos

## Identificación de Riesgos

El lider de equipo de cada grupo de trabajo es el responsable de detectar e informar de potenciales riesgos con la mayor antelacion posible.
La naturaleza de los riesgos reportados puede incluir pero no limitarse a:
* Dificultades tecnicas
* Problemas de personal
* Problemas o retrasos en la comunicación con el cliente

## Reporte de riesgos

Los reportes de los riesgos se deberán enviar a los encargados de Gestión de Riesgos con copia a los gerentes del area de origen del riesgo.
El reporte debe minimamente incluir una descripccion somera del potencial riesgo y una estimacion de la urgencia con la que se debe atender el riesgo. Por ejemplo:

> Urgencia: Alta  
> En la reunion de hoy (dd-mm-aaaa) no se presentaron los contactos con el cliente ni contestaron a los mensajes que se les envio. El equipo de desarrollo necesita confirmacion del cliente para continuar con algunas partes de la aplicacion.

El objetivo de este informe es poner el potencial problema en conocimiento del personal encargado e iniciar la gestion del mismo; no es necesario que sea excesivamente detallado o tecnico.

## Analisis de riesgos

El analisis del riesgo propiamente dicho sera llevado a cabo por el personal de Gestion de Riesgos en colaboracion con las areas afectadas por el riesgo. Es responsabilidad de estas ultimas colaborar en el analisis del riesgo y elaboracion del Plan de Manejo y Monitoreo.

#### Modelo de un analisis

> Nombre: Retrasos en la comunicacion con el cliente  
> Descripcion: Regularmente resulta imposible comunicarse con el cliente por los medios habituales; lo que produce demoras en la velocidad de avance del proyecto.  
> Categorias afectadas: Cronograma, Calidad del producto
> Impacto: Bajo  
> Frecuencia: Alta  
> Plan de Manejo y Monitoreo:  
> 1. Coordinar los encuentros con el cliente con mayor antelacion
> 2. Establecer una serie de tareas alternativas con las que continuar el proyecto en caso de que el cliente demore en validar lo hecho
> 3. Acordar con el cliente medio de contacto alternativos en caso de emergencia
